name: Chad Thiele
favicon: null
layout_spectrum: 0.6697651685681194
typography_spectrum: 0.6779751966241747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8617726953234524
  lightness: 0.9109739956911653
  saturation: 0.9354194782208651
  rhythmicContrast: 0.6847285218536854
purpose: []
